const altText = [
  // SFX alt text
  {
    1: "A woman painted as a witch",
    2: "A man painted as wooden puppet",
    3: "A man painted as a lion next to a man painted as a lion tamer in a circus",
    4: "A man painted as zombie covered in blood",
    5: "A woman with completely white eyes and thick blood dripping from the top of her head halfway in water",
    6: "A cardboard cutout of a clown head",
    7: "A woman painted to look like a leopard with black claw hands making a growling face",
    8: "A side by side of a man with no makeup and then the same man with a red devil makeup look with big horns at the top of his head",
    9: "A man painted as a werewolf with a bone necklace",
    10: "A man with a gray-blue skull makeup look and completely black eyes",
    11: "A woman dressed as the witch Maleficent from Snow White",
    12: "A man painted as a green sea goblin-type creature with horns going across from his nose to the back of his head and claws",
    13: "A woman painted as the Corpse Bride",
    14: "A man painted as a royal person with pink hair and a pink moustache and makeup and a painted on outfit including a pink fluffy cape and yellow armor",
    15: "A woman with a colorful flames skull makeup look",
    16: "A woman painted as an Avatar with long red hair in a crouched position",
  },
  // Bridal alt text
  {
    1: "A woman with bridal makeup on",
    2: "A woman with bridal makeup on",
    3: "A woman in a traditional Indian wedding gown and bridal makeup",
    4: "A woman posing in a seated position in a white wedding dress with her eyes closed",
    5: "Melvin doing a bride's makeup as she smiles",
    6: "A woman with bridal makeup on",
    7: "A woman in a traditional Indian wedding gown and bridal makeup with her eyes closed",
    8: "A woman posing in a seated position in a white wedding dress",
    9: "A woman with bridal makeup on",
    10: "Melvin applying lipstick to a seated bride",
  },
  // Makeup alt text
  {
    1: "A woman with glam makeup on",
    2: "A woman with glam makeup on",
    3: "A woman with glam makeup on sticking her tongue out",
    4: "A man with orange and blue smoked out eyeshadow on",
    5: "A woman with glam makeup on",
    6: "A woman with glam makeup on",
    7: "A woman with glam makeup on",
    8: "Melvin with glam makeup on",
    9: "A woman with glam makeup and a blue cut-crease eyeshadow on",
    10: "A woman with glam makeup on",
    11: "A pregnant woman with a white dress and makeup on posing in a seated position",
    12: "A woman with glam makeup on",
    13: "A woman with glam makeup and a purple cut-crease eyeshadow on",
    14: "A woman with glam makeup on",
    15: "A woman with glam makeup and long black gloves on posing with her hands under her face",
    16: "Melvin doing glam makeup on a blonde woman",
  },
];

export default altText;
